#define SDL_MAIN_HANDLED
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <stdint.h>
#include <stddef.h>
#include "win_include.h"
#include <SDL2/SDL.h>
#include <SDL2/SDL_mixer.h>
#include <cglm/call.h>
#include <cglm/struct.h>
#include "glad.c"
#include <glad/glad.h>
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"
#include <ft2build.h>
#include FT_FREETYPE_H
#include "engine.h"
#include "definitions.c"
#include "shader.c"
#include "texture.c"
#include "lights.c"
#include "audio.c"
#include "buffers.c"
#include "bloom.c"
#include "init.c"
#include "update.c"
#include "draw.c"