void DrawQuad();
void DrawRect(Rectangle rec, Vector4 color);
void DrawUIRect(Rectangle rec, Vector4 color);
void DrawUITexRect(Rectangle rec);
void DrawTexRect(Rectangle rec);
void DrawTexRectTint(Rectangle rec, Vector4 tint);
void DrawWorldText(char *text, Font *font, float x, float y, float scale, Vector4 color);
void DrawWorldTextText(Text text, Font *font);
void DrawText(char *text, Font *font, float x, float y, float scale, Vector4 color);
void DrawTextText(Text text, Font *font);
void DrawSubText(char *text, Font *font, int count, float x, float y, float scale, Vector4 color);
void DrawSubTextText(Text *text, Font *font, int count);
void DrawGradientV(Vector4 start, Vector4 end, float offset);