void DrawQuad();
void DrawCube(Vector3 pos, Vector3 rotation, Vector3 scale, Texture texture);
void DrawRect(Rectangle rec, Texture tex, float rotation, unsigned int shader);
Vertex *CreateQuad(Vertex *target, float x, float y, float width, float height, float rotation, float tex);
void DrawUIRect(Rectangle rec, Vector4 color);
void DrawUITexRect(Rectangle rec);
void DrawTexRect(Rectangle rec);
void DrawTexRectTint(Rectangle rec, Vector4 tint);
void DrawWorldText(char *text, Font *font, float x, float y, float scale, Vector4 color);
void DrawWorldTextText(Text text, Font *font);
void DrawText(char *text, Font *font, float x, float y, float scale, Vector4 color);
void DrawTextText(Text text, Font *font);
void DrawSubText(char *text, Font *font, int count, float x, float y, float scale, Vector4 color);
void DrawSubTextText(Text *text, Font *font, int count);
void DrawGradientV(Vector4 start, Vector4 end, float offset);
void DrawLine2DWorld(Vector2 start, Vector2 end, Vector4 color);